from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Attribute(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, value=None, datatype=None):  # noqa: E501
        """Attribute - a model defined in OpenAPI

        :param name: The name of this Attribute.  # noqa: E501
        :type name: str
        :param value: The value of this Attribute.  # noqa: E501
        :type value: str
        :param datatype: The datatype of this Attribute.  # noqa: E501
        :type datatype: str
        """
        self.openapi_types = {
            'name': str,
            'value': str,
            'datatype': str
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value',
            'datatype': 'datatype'
        }

        self._name = name
        self._value = value
        self._datatype = datatype

    @classmethod
    def from_dict(cls, dikt) -> 'Attribute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The attribute of this Attribute.  # noqa: E501
        :rtype: Attribute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Attribute.


        :return: The name of this Attribute.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Attribute.


        :param name: The name of this Attribute.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> str:
        """Gets the value of this Attribute.


        :return: The value of this Attribute.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Attribute.


        :param value: The value of this Attribute.
        :type value: str
        """

        self._value = value

    @property
    def datatype(self) -> str:
        """Gets the datatype of this Attribute.


        :return: The datatype of this Attribute.
        :rtype: str
        """
        return self._datatype

    @datatype.setter
    def datatype(self, datatype: str):
        """Sets the datatype of this Attribute.


        :param datatype: The datatype of this Attribute.
        :type datatype: str
        """

        self._datatype = datatype
