from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AudioBlobRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, audio_blob=None):  # noqa: E501
        """AudioBlobRequest - a model defined in OpenAPI

        :param audio_blob: The audio_blob of this AudioBlobRequest.  # noqa: E501
        :type audio_blob: str
        """
        self.openapi_types = {
            'audio_blob': str
        }

        self.attribute_map = {
            'audio_blob': 'audio_blob'
        }

        self._audio_blob = audio_blob

    @classmethod
    def from_dict(cls, dikt) -> 'AudioBlobRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AudioBlobRequest of this AudioBlobRequest.  # noqa: E501
        :rtype: AudioBlobRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def audio_blob(self) -> str:
        """Gets the audio_blob of this AudioBlobRequest.


        :return: The audio_blob of this AudioBlobRequest.
        :rtype: str
        """
        return self._audio_blob

    @audio_blob.setter
    def audio_blob(self, audio_blob: str):
        """Sets the audio_blob of this AudioBlobRequest.


        :param audio_blob: The audio_blob of this AudioBlobRequest.
        :type audio_blob: str
        """

        self._audio_blob = audio_blob
