from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetJobObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None, role=None, hr_email=None):  # noqa: E501
        """GetJobObject - a model defined in OpenAPI

        :param job_id: The job_id of this GetJobObject.  # noqa: E501
        :type job_id: int
        :param role: The role of this GetJobObject.  # noqa: E501
        :type role: str
        :param hr_email: The hr_email of this GetJobObject.  # noqa: E501
        :type hr_email: str
        """
        self.openapi_types = {
            'job_id': int,
            'role': str,
            'hr_email': str
        }

        self.attribute_map = {
            'job_id': 'job_id',
            'role': 'role',
            'hr_email': 'hr_email'
        }

        self._job_id = job_id
        self._role = role
        self._hr_email = hr_email

    @classmethod
    def from_dict(cls, dikt) -> 'GetJobObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetJobObject of this GetJobObject.  # noqa: E501
        :rtype: GetJobObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> int:
        """Gets the job_id of this GetJobObject.


        :return: The job_id of this GetJobObject.
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: int):
        """Sets the job_id of this GetJobObject.


        :param job_id: The job_id of this GetJobObject.
        :type job_id: int
        """

        self._job_id = job_id

    @property
    def role(self) -> str:
        """Gets the role of this GetJobObject.


        :return: The role of this GetJobObject.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this GetJobObject.


        :param role: The role of this GetJobObject.
        :type role: str
        """

        self._role = role

    @property
    def hr_email(self) -> str:
        """Gets the hr_email of this GetJobObject.


        :return: The hr_email of this GetJobObject.
        :rtype: str
        """
        return self._hr_email

    @hr_email.setter
    def hr_email(self, hr_email: str):
        """Sets the hr_email of this GetJobObject.


        :param hr_email: The hr_email of this GetJobObject.
        :type hr_email: str
        """

        self._hr_email = hr_email
