from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class JobRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, role=None, hr_email=None):  # noqa: E501
        """JobRequest - a model defined in OpenAPI

        :param id: The id of this JobRequest.  # noqa: E501
        :type id: int
        :param role: The role of this JobRequest.  # noqa: E501
        :type role: str
        :param hr_email: The hr_email of this JobRequest.  # noqa: E501
        :type hr_email: str
        """
        self.openapi_types = {
            'id': int,
            'role': str,
            'hr_email': str
        }

        self.attribute_map = {
            'id': 'id',
            'role': 'role',
            'hr_email': 'hr_email'
        }

        self._id = id
        self._role = role
        self._hr_email = hr_email

    @classmethod
    def from_dict(cls, dikt) -> 'JobRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobRequest of this JobRequest.  # noqa: E501
        :rtype: JobRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this JobRequest.


        :return: The id of this JobRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this JobRequest.


        :param id: The id of this JobRequest.
        :type id: int
        """

        self._id = id

    @property
    def role(self) -> str:
        """Gets the role of this JobRequest.


        :return: The role of this JobRequest.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this JobRequest.


        :param role: The role of this JobRequest.
        :type role: str
        """

        self._role = role

    @property
    def hr_email(self) -> str:
        """Gets the hr_email of this JobRequest.


        :return: The hr_email of this JobRequest.
        :rtype: str
        """
        return self._hr_email

    @hr_email.setter
    def hr_email(self, hr_email: str):
        """Sets the hr_email of this JobRequest.


        :param hr_email: The hr_email of this JobRequest.
        :type hr_email: str
        """

        self._hr_email = hr_email
