from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class QuestionObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, questions=None):  # noqa: E501
        """QuestionObject - a model defined in OpenAPI

        :param questions: The questions of this QuestionObject.  # noqa: E501
        :type questions: List[str]
        """
        self.openapi_types = {
            'questions': List[str]
        }

        self.attribute_map = {
            'questions': 'questions'
        }

        self._questions = questions

    @classmethod
    def from_dict(cls, dikt) -> 'QuestionObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QuestionObject of this QuestionObject.  # noqa: E501
        :rtype: QuestionObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def questions(self) -> List[str]:
        """Gets the questions of this QuestionObject.


        :return: The questions of this QuestionObject.
        :rtype: List[str]
        """
        return self._questions

    @questions.setter
    def questions(self, questions: List[str]):
        """Sets the questions of this QuestionObject.


        :param questions: The questions of this QuestionObject.
        :type questions: List[str]
        """

        self._questions = questions
