from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, name=None, role=None, question=None, answer=None, percentage=None, result=None, recordingpath=None):  # noqa: E501
        """UserRequest - a model defined in OpenAPI

        :param email: The email of this UserRequest.  # noqa: E501
        :type email: str
        :param name: The name of this UserRequest.  # noqa: E501
        :type name: str
        :param role: The role of this UserRequest.  # noqa: E501
        :type role: str
        :param question: The question of this UserRequest.  # noqa: E501
        :type question: str
        :param answer: The answer of this UserRequest.  # noqa: E501
        :type answer: str
        :param percentage: The percentage of this UserRequest.  # noqa: E501
        :type percentage: int
        :param result: The result of this UserRequest.  # noqa: E501
        :type result: str
        :param recordingpath: The recordingpath of this UserRequest.  # noqa: E501
        :type recordingpath: str
        """
        self.openapi_types = {
            'email': str,
            'name': str,
            'role': str,
            'question': str,
            'answer': str,
            'percentage': int,
            'result': str,
            'recordingpath': str
        }

        self.attribute_map = {
            'email': 'email',
            'name': 'name',
            'role': 'role',
            'question': 'question',
            'answer': 'answer',
            'percentage': 'percentage',
            'result': 'result',
            'recordingpath': 'recordingpath'
        }

        self._email = email
        self._name = name
        self._role = role
        self._question = question
        self._answer = answer
        self._percentage = percentage
        self._result = result
        self._recordingpath = recordingpath

    @classmethod
    def from_dict(cls, dikt) -> 'UserRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRequest of this UserRequest.  # noqa: E501
        :rtype: UserRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this UserRequest.


        :return: The email of this UserRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserRequest.


        :param email: The email of this UserRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def name(self) -> str:
        """Gets the name of this UserRequest.


        :return: The name of this UserRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserRequest.


        :param name: The name of this UserRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def role(self) -> str:
        """Gets the role of this UserRequest.


        :return: The role of this UserRequest.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserRequest.


        :param role: The role of this UserRequest.
        :type role: str
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def question(self) -> str:
        """Gets the question of this UserRequest.


        :return: The question of this UserRequest.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question: str):
        """Sets the question of this UserRequest.


        :param question: The question of this UserRequest.
        :type question: str
        """
        if question is None:
            raise ValueError("Invalid value for `question`, must not be `None`")  # noqa: E501

        self._question = question

    @property
    def answer(self) -> str:
        """Gets the answer of this UserRequest.


        :return: The answer of this UserRequest.
        :rtype: str
        """
        return self._answer

    @answer.setter
    def answer(self, answer: str):
        """Sets the answer of this UserRequest.


        :param answer: The answer of this UserRequest.
        :type answer: str
        """

        self._answer = answer

    @property
    def percentage(self) -> int:
        """Gets the percentage of this UserRequest.


        :return: The percentage of this UserRequest.
        :rtype: int
        """
        return self._percentage

    @percentage.setter
    def percentage(self, percentage: int):
        """Sets the percentage of this UserRequest.


        :param percentage: The percentage of this UserRequest.
        :type percentage: int
        """

        self._percentage = percentage

    @property
    def result(self) -> str:
        """Gets the result of this UserRequest.


        :return: The result of this UserRequest.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this UserRequest.


        :param result: The result of this UserRequest.
        :type result: str
        """

        self._result = result

    @property
    def recordingpath(self) -> str:
        """Gets the recordingpath of this UserRequest.


        :return: The recordingpath of this UserRequest.
        :rtype: str
        """
        return self._recordingpath

    @recordingpath.setter
    def recordingpath(self, recordingpath: str):
        """Sets the recordingpath of this UserRequest.


        :param recordingpath: The recordingpath of this UserRequest.
        :type recordingpath: str
        """

        self._recordingpath = recordingpath
